<a href="https://colab.research.google.com/github/Sadia7766/Assignment/blob/main/SM_assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sadia Akter (2215151033)_7A2

Tasks:

Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
   Run the code twice
  With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
  Without setting a seed, allowing random values to change each time.  
  Observe and explain the differences in outputs.  (in a different cell as text)

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Seeded Random Matrix:\n", seeded_matrix)

Seeded Random Matrix:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [ ]:
np.random.seed(None)
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("\nNon-Seeded Random Matrix:\n", non_seeded_matrix)


Non-Seeded Random Matrix:
 [[49 48 19]
 [16 46 49]
 [42  8 28]]


When np.random.seed() is used with a specific number (e.g., 10), it establishes the random number generator with a specific starting point.This means the seed will be the same every time the code is run with the same seed value.

On the other hand, if you don't set a seed, the random number generator produces different numbers each time I run the code. This means that the matrix will change every time with different random integers.